pool: Selfhosted-Bootcamp
demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false

  # Download secure file from azure library
- task: DownloadSecureFile@1
  inputs:
   secureFile: '.env.production'

  # Copy the .env file
- task: CopyFiles@2
  inputs:
      sourceFolder: '$(Agent.TempDirectory)'
      contents: '**/*.env.production'
      targetFolder: '.'
      cleanTargetFolder: false

- task: Npm@1
  displayName: 'npm run build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: build
